import { Document, Packer, Paragraph, TextRun } from "docx";
import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { buildJsonExport, buildTextExport } from "@/features/export/export-readiness";
import type { AnalysisPayload } from "@/types/resume";

export const runtime = "nodejs";

type ExportBody = {
  payload: AnalysisPayload;
  format: "txt" | "json" | "docx" | "pdf";
  filename?: string;
};

function safeFilename(name?: string) {
  return (name || "KindlyCV_AI_Resume").replace(/[^a-zA-Z0-9_-]+/g, "_");
}

async function buildDocx(text: string) {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: text.split(/\n/).map(
          (line) =>
            new Paragraph({
              children: [new TextRun({ text: line, size: line === line.toUpperCase() ? 28 : 22, bold: line === line.toUpperCase() })],
              spacing: { after: 120 }
            })
        )
      }
    ]
  });
  return Packer.toBuffer(doc);
}

function isHeading(line: string) {
  const trimmed = line.trim();
  const commonHeadings = new Set([
    "summary",
    "objective",
    "skills",
    "technical skills",
    "experience",
    "work experience",
    "projects",
    "education",
    "certifications",
    "awards",
    "awards & certifications",
    "achievements"
  ]);
  return (
    trimmed.length > 0 &&
    trimmed.length < 54 &&
    (trimmed === trimmed.toUpperCase() || commonHeadings.has(trimmed.toLowerCase()))
  );
}

function sanitizePdfText(text: string) {
  return text
    .replace(/[\u2012-\u2015]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, "\"")
    .replace(/\u2022/g, "-")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x09\x0a\x0d\x20-\x7e]/g, "")
    .replace(/\s*#\s*(?=[^\s@]+@[^\s@]+)/g, " | ")
    .replace(/^i\s+(?=(linkedin|github|https?:\/\/|www\.))/i, "")
    .replace(/\s*\|\s*/g, " | ")
    .replace(/([a-z)])(January|February|March|April|May|June|July|August|September|October|November|December)/g, "$1 $2")
    .replace(/([a-z)])((?:19|20)\d{2})/gi, "$1 $2")
    .replace(/\s{2,}/g, " ")
    .trim();
}

async function buildPdf(text: string, candidateName: string) {
  return new Promise<Buffer>((resolve, reject) => {
    const safeCandidateName = sanitizePdfText(candidateName || "Improved Resume");
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: 54, bottom: 54, left: 56, right: 56 },
      info: {
        Title: `${safeCandidateName} Improved Resume`,
        Subject: "Improved ATS-friendly resume generated by KindlyCV AI",
        Author: safeCandidateName || "KindlyCV AI"
      }
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const lines = text.split(/\r?\n/);
    doc.fillColor("#111827");

    lines.forEach((line, index) => {
      const trimmed = sanitizePdfText(line);
      if (!trimmed) {
        doc.moveDown(0.45);
        return;
      }

      if (index === 0) {
        doc.font("Helvetica-Bold").fontSize(18).text(trimmed, { align: "center" });
        doc.moveDown(0.3);
        return;
      }

      if (isHeading(trimmed)) {
        doc.moveDown(0.45);
        doc.font("Helvetica-Bold").fontSize(11).fillColor("#1f2937").text(trimmed.toUpperCase(), {
          characterSpacing: 0.6
        });
        doc.moveTo(doc.x, doc.y + 2).lineTo(556, doc.y + 2).strokeColor("#d1d5db").lineWidth(0.5).stroke();
        doc.moveDown(0.3);
        return;
      }

      const bulletLike = /^[-*]\s+/.test(trimmed);
      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#111827")
        .text(bulletLike ? trimmed.replace(/^[-*]\s+/, "- ") : trimmed, {
          align: "left",
          lineGap: 2,
          continued: false
        });
    });

    doc.end();
  });
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as ExportBody;
    const filename = safeFilename(body.filename);

    if (body.format === "json") {
      return new NextResponse(buildJsonExport(body.payload), {
        headers: {
          "content-type": "application/json",
          "content-disposition": `attachment; filename="${filename}.json"`
        }
      });
    }

    if (body.format === "docx") {
      const buffer = await buildDocx(buildTextExport(body.payload));
      return new NextResponse(new Uint8Array(buffer), {
        headers: {
          "content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "content-disposition": `attachment; filename="${filename}.docx"`
        }
      });
    }

    if (body.format === "pdf") {
      const buffer = await buildPdf(buildTextExport(body.payload), body.payload.resume.contact.fullName);
      return new NextResponse(new Uint8Array(buffer), {
        headers: {
          "content-type": "application/pdf",
          "content-disposition": `attachment; filename="${filename}.pdf"`
        }
      });
    }

    return new NextResponse(buildTextExport(body.payload), {
      headers: {
        "content-type": "text/plain; charset=utf-8",
        "content-disposition": `attachment; filename="${filename}.txt"`
      }
    });
  } catch (error) {
    console.error("Resume export failed", error);
    return NextResponse.json({ error: "Export failed. Check readiness issues and try again." }, { status: 400 });
  }
}
